### ISSUE TITLE
Not able to type

### ISSUE THREAD

**Issue by ghost** [chromakode/xkcdfools#7]
I really love what you've done. But I setup the source code on my webspace but I'm not able to type anything. The Alt and Control buttons though work alright.  But on the XKCD site I can type one the site perfectly.

I first downloaded the files individually when that didn't work i downloaded a zip source archive, but the same problem.

Any idea? Thanks!

**Comment by chromakode** [comment]
Due to the same-origin policy, you need to run some kind of proxy to be able to reach JSON on xkcd.com. I use this proxy on my testing system:

http://benalman.com/projects/php-simple-proxy/

The "xkcd" object in source file xkcd_cli.js has a parameter where you can set a proxy location.

Note: there's one confounding issue -- the currently uploaded source tree is missing some error handling that's live. The version pushed here will freeze the terminal if it can't hit "/info.0.json" successfully. I won't be pushing to the tree until people have had a chance to explore our new changes. Stay tuned for updates that will handle this problem better.

**Comment by ghost** [comment]
Thank you for your quick response! I will monitor the updates.
